# -*- coding: utf-8 -*-
"""Lab1_P1_Zavala_Angel.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qwR3XI6dZgDNSuZRAk2PhMQECWcDJ9CV

# Lab 1. Creating a Class, Object, Attribute & Methods.

Student: Zavala Flores Angel
Object-Oriented Programming 4ºB BIS

In this Lab you are going to explore and create a program that defines a class called Air Fryer
"""

from typing import Self
class air_fryer:
  def __init__(self, color, brand, size):
    self.color = color
    self.brand = brand
    self.size = size

  def dehydrate(self):
    print("The food is dehydrating...")

  def fry(self):
    print("The food is frying...")

  def defrost(self):
    print("The food is defrosting...")

  def describe(self):
    print(f"This Air Fryer is by {self.brand}",
          f"the color is {self.color}",
          f"and the size is {self.size}")

#self: Se utiliza para decirle a Python a que objeto pertenecen los atributos.
#create an instance using the class "air_fryer"
air_fryer1 = air_fryer("Red", "Ninja", "10 in²")
air_fryer2 = air_fryer("Black", "Cosori", "12 in²")

#We access to the object (Instance) "air_fryer1" to call its data.
print(air_fryer1.brand)
print(air_fryer1.color)
air_fryer1.defrost()
air_fryer1.describe()

#Instance "air_fryer2"
print(air_fryer2.brand)
print(air_fryer2.color)
air_fryer2.defrost()
air_fryer2.describe()

"""# Lab 1: Bank Account Class
Create a Python program that models a bank account using Object-Oriented Programming.
"""

class bank_account:
  def __init__(self, holder_name, balance):
    self.holder_name = holder_name
    self.balance = float(balance)

  def deposit(self):
    proceed = True
    while proceed:
      amount = float(input("Amount to deposit: $"))
      if amount <= 0:
        print("The amount has to be more than 0...")
      elif amount > 0:
        self.balance += amount
        print(f"Successfully deposited ${amount:.2f}",
              f"New Balance: ${self.balance:.2f}")
        proceed = False
      else:
        print("Invalid input. Please enter a numeric value...")

  def withdraw(self):
    proceed = True
    while proceed:
      amount = float(input("Amount to withdraw: $"))
      if amount <= 0:
        print("The amount has to be more than 0...")
      elif amount > self.balance:
        print("The amount assigned exceed with the current balance...")
      elif amount <= self.balance:
        self.balance -= amount
        print(f"Successfully withdrawn ${amount:.2f}",
              f"New Balance: ${self.balance:.2f}")
        proceed = False
      else:
        print("Inavlid input. Please enter a numeric value")

  def check_balance(self):
    print(f"Current Balance: ${self.balance:.2f}")

bank_account1 = bank_account("Raúl Pérez", 5000)
bank_account2 = bank_account("Joel López", 3000)

print(bank_account1.holder_name)
print(bank_account1.balance)
bank_account1.deposit()
bank_account1.withdraw()
bank_account1.check_balance()